#**ЗАВДАННЯ 1**

1. одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.


In [ ]:
import numpy as np

result = np.arange(1,11)
print(result)

[ 1  2  3  4  5  6  7  8  9 10]


2. двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.


In [ ]:
import numpy as np

result = np.zeros((3,3),dtype=int)
print(result)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


3. масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.


In [ ]:
import numpy as np

result = np.random.randint(1,11, size=(5,5))
print(result)

[[ 7 10  9  4  1]
 [ 9  1  2  6  6]
 [10  5  9  6  8]
 [ 4  4  6  6  4]
 [ 4 10  1  2  3]]


4. масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.


In [ ]:
import numpy as np

result = np.random.random((4,4))
print(result)

[[0.98847977 0.22786107 0.41631064 0.56561094]
 [0.50485989 0.10076118 0.89047597 0.65280795]
 [0.47768575 0.64422794 0.366387   0.49547907]
 [0.74699521 0.67988494 0.88862182 0.91256945]]


5. два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.


In [ ]:
import numpy as np

a = np.random.randint(1,11, size=5)
print(f'a = {a}')
b = np.random.randint(1,11, size=5)
print(f'b = {b}')

result = a + b
print(f'a + b = {result}')

result = a - b
print(f'a - b = {result}')

result = a * b
print(f'a * b = {result}')

a = [2 5 1 5 4]
b = [ 7  6  7  3 10]
a + b = [ 9 11  8  8 14]
a - b = [-5 -1 -6  2 -6]
a * b = [14 30  7 15 40]


6. два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.


In [ ]:
import numpy as np

a = np.random.randint(1,11, size=7)
print(f'a = {a}')
b = np.random.randint(1,11, size=7)
print(f'b = {b}')

result = np.dot(a,b)
print(f'a ⋅ b = {result}')

a = [7 2 7 9 7 1 9]
b = [10  2  1 10  2 10  6]
a ⋅ b = 249


7. дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.


In [ ]:
import numpy as np

a = np.random.randint(1,11, size=(2,2))
print(f'A = \n{a}\n')
b = np.random.randint(1,11, size=(2,3))
print(f'B = \n{b}\n')

result = np.dot(a,b)
print(f'A ⋅ B = \n{result}\n')

A = 
[[4 3]
 [1 1]]

B = 
[[ 8 10  5]
 [ 1  4  7]]

A ⋅ B = 
[[35 52 41]
 [ 9 14 12]]



8. матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.


In [ ]:
import numpy as np

a = np.random.randint(1,11, size=(3,3))
print(f'A = \n{a}\n')

result = np.linalg.inv(a)
print(f'A^(-1) = \n{result}\n')

A = 
[[2 7 2]
 [5 2 8]
 [5 6 3]]

A^(-1) = 
[[-0.32061069 -0.06870229  0.39694656]
 [ 0.19083969 -0.03053435 -0.04580153]
 [ 0.15267176  0.17557252 -0.23664122]]



9. матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.


In [ ]:
import numpy as np

a = np.random.random((4,4))
print(f'A = \n{a}\n')

result = a.T
print(f'A^T = \n{result}\n')

A = 
[[0.08587803 0.52069993 0.67634146 0.85831295]
 [0.51364469 0.7216486  0.59018849 0.53016367]
 [0.56976313 0.91879647 0.75178256 0.01420025]
 [0.21917155 0.60851613 0.98244462 0.39176512]]

A^T = 
[[0.08587803 0.51364469 0.56976313 0.21917155]
 [0.52069993 0.7216486  0.91879647 0.60851613]
 [0.67634146 0.59018849 0.75178256 0.98244462]
 [0.85831295 0.53016367 0.01420025 0.39176512]]



10. матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.


In [ ]:
import numpy as np

a = np.random.randint(1,11, size=(3,4))
print(f'A = \n{a}\n')
b = np.random.randint(1,11, size=4)
print(f'b = {b}\n')

result = np.dot(a,b)
print(f'A ⋅ b = {result}\n')

A = 
[[ 5  9  1  3]
 [ 5 10  9  6]
 [ 8 10 10  8]]

b = [3 5 5 1]

A ⋅ b = [ 68 116 132]



11. матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.


In [ ]:
import numpy as np

a = np.random.randint(1,11, size=(2,3))
print(f'A = \n{a}\n')
b = np.random.randint(1,11, size=3)
print(f'b = {b}\n')

result = np.dot(a,b)
print(f'A ⋅ b = {result}\n')

A = 
[[10  6  3]
 [ 5  3  6]]

b = [10  6  8]

A ⋅ b = [160 116]



12. дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.


In [ ]:
import numpy as np

a = np.random.randint(1,11, size=(2,2))
print(f'A = \n{a}\n')
b = np.random.randint(1,11, size=(2,2))
print(f'B = \n{b}\n')

result = a * b
print(f'A * B = \n{result}\n')

A = 
[[8 9]
 [4 9]]

B = 
[[7 7]
 [5 9]]

A * B = 
[[56 63]
 [20 81]]



13. дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [ ]:
import numpy as np

a = np.random.randint(1,11, size=(2,2))
print(f'A = \n{a}\n')
b = np.random.randint(1,11, size=(2,2))
print(f'B = \n{b}\n')

result = np.dot(a,b)
print(f'A ⋅ B = \n{result}\n')

A = 
[[8 5]
 [3 9]]

B = 
[[5 6]
 [2 6]]

A ⋅ B = 
[[50 78]
 [33 72]]



14. матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.


In [ ]:
import numpy as np

a = np.random.randint(1,101, size=(5,5))
print(f'A = \n{a}\n')

result = a.sum()
print(f'sum(A) = {result}\n')

A = 
[[  9  67  86  77  20]
 [ 80  39 100  95  42]
 [ 39 100  85   8  32]
 [ 68  66  87   4  50]
 [ 72  80  79  80  81]]

sum(A) = 1546



15. дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.


In [ ]:
import numpy as np

a = np.random.randint(1,11, size=(4,4))
print(f'A = \n{a}\n')
b = np.random.randint(1,11, size=(4,4))
print(f'B = \n{b}\n')

result = a - b
print(f'A - B = \n{result}\n')

A = 
[[ 2  5  5  3]
 [ 1  6  7  7]
 [ 8  6 10  8]
 [ 3  9  8  6]]

B = 
[[ 1  3  9  3]
 [10  5  1  5]
 [ 8  1  7  6]
 [ 6  1  4  8]]

A - B = 
[[ 1  2 -4  0]
 [-9  1  6  2]
 [ 0  5  3  2]
 [-3  8  4 -2]]



16. матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.


In [ ]:
import numpy as np

a = np.random.random((3,3))
print(f'A = \n{a}\n')

result = a.sum(axis=1).reshape(-1, 1)
print(f'sum(A) = \n{result}\n')

A = 
[[0.05977748 0.90822627 0.50137692]
 [0.87678535 0.20185883 0.63026246]
 [0.81849483 0.56700521 0.03336489]]

sum(A) = 
[[1.46938068]
 [1.70890665]
 [1.41886493]]



17. матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.


In [ ]:
import numpy as np

a = np.random.randint(1,11, size=(3,4))
print(f'A = \n{a}\n')

result = np.square(a)
print(f'A^2 = \n{result}\n')

A = 
[[ 6  1  6 10]
 [ 6  8 10  7]
 [ 2  9  9  1]]

A^2 = 
[[ 36   1  36 100]
 [ 36  64 100  49]
 [  4  81  81   1]]



18. вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [ ]:
import numpy as np

a = np.random.randint(1,51, size=4)
print(f'a = {a}\n')

result = np.sqrt(a)
print(f'sqrt(a) = {result}\n')

a = [20 39  3 14]

sqrt(a) = [4.47213595 6.244998   1.73205081 3.74165739]



# **ЗАВДАННЯ 2**

1. Замініть усі непарні числа в arr на -1 arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(f'arr = {arr}\n')

arr[arr % 2 == 1] = -1
print(f'arr = {arr}')

arr = [0 1 2 3 4 5 6 7 8 9]

arr = [ 0 -1  2 -1  4 -1  6 -1  8 -1]


2. Створіть та перетворіть 1D-масив на 2D-масив із 2 рядками


In [ ]:
import numpy as np

arr = np.arange(10)
print(f'arr = {arr}\n')

arr = arr.reshape(2, -1)
print(f'arr = \n{arr}')

arr = [0 1 2 3 4 5 6 7 8 9]

arr = 
[[0 1 2 3 4]
 [5 6 7 8 9]]


3. Створіть два двовимірні масиви а і b, та складіть масиви їх вертикально


In [ ]:
import numpy as np

a = np.arange(10).reshape(2, -1)
print(f'A = \n{a}\n')
b = np.arange(10).reshape(2, -1)
print(f'B = \n{b}\n')

result = np.vstack((a, b))
print(f'vertical stack (A , B) = \n{result}')

A = 
[[0 1 2 3 4]
 [5 6 7 8 9]]

B = 
[[0 1 2 3 4]
 [5 6 7 8 9]]

vertical stack (A , B) = 
[[0 1 2 3 4]
 [5 6 7 8 9]
 [0 1 2 3 4]
 [5 6 7 8 9]]


4. Створіть наступний шаблон без жорсткого кодування(Hard coding) . Використовуйте лише функції Numpy і наведений нижче масив введення Input:a = np.array([1,2,3])

Output:array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
import numpy as np

a = np.array([1,2,3])
print(f'a = {a}\n')

result = np.r_[np.repeat(a, 3), np.tile(a, 3)]
print(f'result = {result}')

a = [1 2 3]

result = [1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


5. Отримайте спільні елементи між a і b

a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])

In [ ]:
import numpy as np

a = np.array([1,2,3,2,3,4,3,4,5,6])
print(f'a = {a}\n')
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(f'b = {b}\n')

result = np.intersect1d(a, b)
print(f'result = {result}')

a = [1 2 3 2 3 4 3 4 5 6]

b = [ 7  2 10  2  7  4  9  4  9  8]

result = [2 4]


6. Отримайте позиції перших 5 максимальних значень у заданому масиві a

np.random.seed(100) a = np.random.uniform(1,50, 20)

In [ ]:
import numpy as np

np.random.seed(100)
a = np.random.uniform(1,50, 20)
print(f'a = {a}\n')

result = np.argsort(a)[-5:]
print(f'result = {result}')

a = [27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]

result = [18  7  3 10 15]


7. Вилучіть усі значення NaN із одновимірного масиву

а=np.array([1,2,3,np.nan,5,6,7,np.nan])

In [ ]:
import numpy as np

a = np.array([1,2,3,np.nan,5,6,7,np.nan])
print(f'a = {a}\n')

result = a[~np.isnan(a)]
print(f'result = {result}')

a = [ 1.  2.  3. nan  5.  6.  7. nan]

result = [1. 2. 3. 5. 6. 7.]


8. Обчисліть евклідову відстань між двома масивами a і b.

a = np.array([1,2,3,4,5]) b = np.array([4,5,6,7,8])

In [ ]:
import numpy as np

a = np.array([1,2,3,4,5])
print(f'a = {a}\n')
b = np.array([4,5,6,7,8])
print(f'b = {b}\n')

result = np.linalg.norm(a-b)
print(f'result = {result}')

a = [1 2 3 4 5]

b = [4 5 6 7 8]

result = 6.708203932499369


9. Знайдіть індекс 5-го повторення числа 1 у масиві x

x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

In [ ]:
import numpy as np

x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
print(f'x = {x}\n')

result = np.where(x == 1)[0][4]
print(f'result = {result}')

x = [1 2 1 1 3 4 3 1 1 2 1 1 2]

result = 8


10. Знайдіть повторювані записи (від 2-го випадку повторення і далі) у заданому масиві і позначте їх як True. Перше повторення має бути False.

Input np.random.seed(100) a = np.random.randint(0, 5, 10)

[0 0 3 0 2 4 2 2 2 2] #Output [False True False True False False True True True True]

In [ ]:
import numpy as np

np.random.seed(100)
a = np.random.randint(0, 5, 10)
print(f'a = {a}\n')

result = []
seen = {}

for x in a:
    if x in seen:
        result.append(True)
    else:
        result.append(False)
        seen[x] = 1

print(f'result = {result}')

a = [0 0 3 0 2 4 2 2 2 2]

result = [False, True, False, True, False, False, True, True, True, True]
